# CopilotAdapter.ps1 - GitHub Copilot Instruction Aggregator

function Deploy-CopilotSkills {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ProjectRoot,
        [Parameter(Mandatory=$true)]
        [array]$SkillObjects
    )

    $githubDir = Join-Path $ProjectRoot ".github"
    if (-not (Test-Path $githubDir)) {
        New-Item -ItemType Directory -Path $githubDir -Force | Out-Null
    }

    $copilotFile = Join-Path $githubDir "copilot-instructions.md"
    $builder = [System.Text.StringBuilder]::new()
    $builder.AppendLine("# GitHub Copilot Custom Instructions") | Out-Null
    $builder.AppendLine("<!-- Generated by Nexora Skills Manager -->") | Out-Null
    $builder.AppendLine("") | Out-Null

    $deployed = [System.Collections.Generic.List[string]]::new()

    foreach ($skill in $SkillObjects) {
        $skillMd = Join-Path $skill.Path "SKILL.md"
        if (Test-Path $skillMd) {
            $content = Get-Content $skillMd -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
            $builder.AppendLine("## Skill: $($skill.Id)") | Out-Null
            $builder.AppendLine($content) | Out-Null
            $builder.AppendLine("") | Out-Null
            $deployed.Add($skill.Id)
        }
    }

    Set-Content -Path $copilotFile -Value $builder.ToString() -Encoding UTF8
    return [PSCustomObject]@{
        Platform = "Copilot"
        TargetDirectory = $githubDir
        DeployedSkills = $deployed.ToArray()
    }
}
